111-王耀良-第一次作业
Guigulive/Team-L pull request #10
Opened 2018-03-14 07:39 UTC by nathan0000

lesson1 assignment in myPayroll

2018-03-14 07:39 UTC, nathan0000 commented
please review

2018-03-17 12:51 UTC, nathan0000 commented
lesson 2;

2018-03-17 23:14 UTC, nathan0000 commented
reopen

2018-03-18 02:21 UTC, bap2pecs0 requested changes
第一次作业里面还没有struct，最好分开提交pr

你提交的两次pr都有两次的作业，这个会有merge conflict，你可以分别改一下两次pull request

2018-03-19 01:54 UTC, bap2pecs0 requested changes
第二次作业没有按照要求完成，可以参考一下其他同学的

+### 第二课：课后作业
+完成今天的智能合约添加100ETH到合约中
+- 加入十个员工，每个员工的薪水都是1ETH
+每次加入一个员工后调用calculateRunway这个函数，并且记录消耗的gas是多少？Gas变化么？如果有 为什么？
+- 如何优化calculateRunway这个函数来减少gas的消耗？
+提交：智能合约代码，gas变化的记录，calculateRunway函数的优化

2018-03-24 23:19 UTC, merged