116_陈玲敏_第二课作业修改
Guigulive/Team-L pull request #28
Opened 2018-03-21 02:51 UTC by you7588

@Smillence 
116_陈玲敏_第二课作业修改

2018-03-21 04:12 UTC, bap2pecs0 requested changes
请根据评论修改，另外你不应该close之前的pr，正确的做法是直接update那个pr

2018-03-21 04:12 UTC, Smillence commented on Lesson-2/assignment/第二课作业修改.md
> +   |        | **transaction cost** | **execution cost** |
为啥cost会越来越小？你这个数据应该是不对的，你可以再试试

你这个地方数据和其他同学的差别很大的原因应该是你用了mapping而不是数组

2018-03-21 04:12 UTC, Smillence commented on Lesson-2/assignment/calculateRunway函数的优化.sol
> +    mapping(address => Employee)employees;
第二课还没有用到mapping，这次作业是要求用数组来写

2018-03-21 04:12 UTC, Smillence commented on Lesson-2/assignment/calculateRunway函数的优化.sol
> +        totalSalary -= employees[employeeId].salary * 1 ether;          // *
这个地方是错的，不需要* 1ether，你在addEmployee的已经乘过了

2018-03-21 04:12 UTC, Smillence commented on Lesson-2/assignment/calculateRunway函数的优化.sol
> +        return;
这里不需要return

2018-03-21 04:12 UTC, Smillence commented on Lesson-2/assignment/calculateRunway函数的优化.sol
> +        totalSalary -= employees[employeeId].salary * 1 ether;          // *
同理

2018-03-21 04:12 UTC, Smillence commented on Lesson-2/assignment/calculateRunway函数的优化.sol
> +        totalSalary += employees[employeeId].salary * 1 ether;          // *
同理

2018-03-21 04:12 UTC, Smillence commented on Lesson-2/assignment/calculateRunway函数的优化.sol
> +        return;
不需要return

2018-03-22 12:34 UTC, you7588 commented
@Smillence 已经更改了作业

2018-03-24 22:32 UTC, bap2pecs0 approved these changes

2018-03-25 03:02 UTC, closed without merging