114-何岩-第一次作业
Guigulive/Team-L pull request #7
Opened 2018-03-14 03:21 UTC by kaka3052

114-何岩-第一次作业

2018-03-18 01:45 UTC, Smillence commented on Lesson-1/assignment/payroll.sol
> +        if (employee == 0x0){
这段代码没有必要，你只需要检查msg sender是不是owner，也就是雇主

2018-03-18 01:46 UTC, Smillence commented on Lesson-1/assignment/payroll.sol
> +        if (employee != msg.sender){
这段代码可以改成一行：require(msg.sender == employee);

2018-03-18 01:52 UTC, Smillence commented on Lesson-1/assignment/payroll.sol
> +        if (employee != 0x0 && salary != 0 && hasEnoughFund()){
这个逻辑是不对的，hasEnoughFund的作用是检查“是否有足够支付一次工资circle的余额”，但payLastEmployee不需要有这么多，只需要有salary * ((now - lastPayday)/payDuration)的够了。

2018-03-18 01:56 UTC, Smillence commented on Lesson-1/assignment/payroll.sol
> +            uint payment = salary * ((now - lastPayday)/payDuration);
这个地方有solidity整形的除法要小心，应该写成

`uint payment = salary * (now - lastPayday)/payDuration;`

你那样写的问题是比如员工只工作了半个payDuration，那么`((now - lastPayday)/payDuration)`就等于0，也就是员工拿不到应得的钱

2018-03-18 01:59 UTC, bap2pecs0 reviewed
第一次作业可以根据comments改一下，有一些小问题，整体上通过！

2018-03-19 01:49 UTC, bap2pecs0 requested changes

2018-03-19 01:49 UTC, Smillence commented on Lesson-2/assignment/payroll.sol
> +    //添加新员工，需要对之前的员工工资结算嘛?
不需要

2018-03-19 01:49 UTC, Smillence commented on Lesson-2/assignment/payroll.sol
> +    	assert(index >= 0);
这个地方是错误的，应该是找不到才对，可以改成assert(employee.id == 0x0);

2018-03-19 01:49 UTC, Smillence commented on Lesson-2/assignment/payroll.sol
> +    	assert(index >= 0);
同理，用index判断是不对的。应该改成`assert(employee.id != 0x0);`

原因是员工不存在的话index为0，第一个员工的index也为0

2018-03-19 01:49 UTC, Smillence commented on Lesson-2/assignment/payroll.sol
> +    	assert(index >= 0);
assert(employee.id != 0x0);

2018-03-19 01:49 UTC, Smillence commented on Lesson-2/assignment/payroll.sol
> +        uint totalSalary = 0;
106到109行可以删掉了，不然你这个函数和改进前没有任何变化

2018-03-19 01:49 UTC, Smillence commented on Lesson-2/assignment/payroll.sol
> +    	assert(index >= 0);
assert(employee.id != 0x0);

2018-03-19 01:49 UTC, Smillence commented on Lesson-2/assignment/payroll.sol
> +    	employees[index].lastPayday = now;
这个地方是错误的，如果员工很长时间没有领工资了，那么这样就会导致员工只能领1个月的工资

应该改成`employees[index].lastPayday = nextPayday;`

2018-03-24 23:31 UTC, kaka3052 commented
test

2018-03-24 23:31 UTC, closed without merging