Homework 1
Guigulive/Team-L pull request #9
Opened 2018-03-14 05:14 UTC by lunrongchen

2018-03-17 07:17 UTC, lunrongchen commented
第二次作业

2018-03-18 02:15 UTC, bap2pecs0 reviewed
第一次作业通过！第二次我看了后一起merge

P.S. 下次可以分开提交pr

2018-03-18 23:07 UTC, bap2pecs0 requested changes

2018-03-18 23:07 UTC, Smillence commented on Lesson-2/assignment/yours.sol
> +        totalSalary += salary; //for gas
这个地方应该是+= salary * 1 ether

2018-03-18 23:07 UTC, Smillence commented on Lesson-2/assignment/yours.sol
> +
多余空行

2018-03-18 23:07 UTC, Smillence commented on Lesson-2/assignment/yours.sol
> +        totalSalary -= employee.salary;  //for gas
这个地方不对，你`delete employees[index];`了后employee已经不存在了

2018-03-18 23:07 UTC, Smillence commented on Lesson-2/assignment/yours.sol
> +        totalSalary += salary-employee.salary;
同理，这个地方也不对。有两个错误：1) salary * 1 ether单位错误; 2) employee这个时候salary已经变了

2018-03-24 23:54 UTC, merged